%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/hburgoyne/Dropbox/Matlab/PhD/Zurich
%    Model/ABAQUS_7_24/elastic5.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/07/24 15:15:25

%% Initialize variables.
clear
file = 'plasticJC20_b';
folder = '/Users/hburgoyne/Dropbox/Matlab/PhD/Zurich Model/ABAQUS_7_24/';
ext = '.txt';
filename = strcat(folder,file,ext);
delimiter = ' ';
startRow = 2;
endRow = 102;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t = dataArray{:, 1};
c1 = dataArray{:, 2};
c3 = dataArray{:, 3};
c5 = dataArray{:, 4};
c7 = dataArray{:, 5};
c9 = dataArray{:, 6};
d1 = dataArray{:, 7};
d3 = dataArray{:, 8};
d5 = dataArray{:, 9};
d7 = dataArray{:, 10};
d9 = dataArray{:, 11};

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;

save(file,'t','c1','c3','c5','c7','c9','d1','d3','d5','d7','d9')