function [F] = parameter_minimizer_test(x,deltay,deltap,Fy,Fp,Fy_pr,Fp_pr)

F = x.*((-1)+deltap.*x).^(-1).*((-1)+deltay.*x).^(-1).*(log((-1)+ ...
    deltap.*x)+(-1).*log((-1)+deltay.*x)).^(-1).*((-1).*Fp+Fy+deltay.* ...
    Fp.*x+(-1).*deltap.*Fy.*x+Fp.*((-1)+deltay.*x).*log((-1)+deltap.* ...
    x)+(Fp+(-1).*deltay.*Fp.*x).*log((-1)+deltay.*x)) - Fp_pr;
end

